"""Adding ritmrecord

Revision ID: 070323e53d65
Revises: 09d845120bc0
Create Date: 2025-04-27 16:28:40.031305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070323e53d65'
down_revision = '09d845120bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ritm_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ritm_number', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ritm_record')
    # ### end Alembic commands ###
